spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:9000/oauth2/jwks"

  cloud:
    loadbalancer:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: msv-usuario
              uri: lb://msv-usuario
              predicates:
                - Path=/api/usuarios/**
              filters:
                - StripPrefix=1
            
            # Rutas para documentaci贸n OpenAPI de cada microservicio
            - id: msv-usuario-api-docs
              uri: lb://msv-usuario
              predicates:
                - Path=/v3/api-docs/usuarios
              filters:
                - RewritePath=/v3/api-docs/usuarios, /v3/api-docs

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true

# Configuraci贸n de Actuator
management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      access: unrestricted

# Configuraci贸n de Springdoc OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  # Configuraci贸n para Spring Cloud Gateway
  enable-spring-cloud-gateway: true
  show-actuator: false